const ASSETS = {
  PUBLIC: {
    TAG_LOGO: "/incridea2025/badgelogo.webp",
    LOGO_I: "/incridea2025/about/logo.webp",
    LOGO_RIM: "/incridea2025/vertical_logo.webp",
    LOGO_RIM_WHITE: "/incridea2025/logo-rim-white.webp",
    LOGO_BLACK: "/incridea2025/logo.webp",
    LOGO_WHITE: "/incridea2025/logo-white.webp",
    LOGO_COMBINED: "/incridea2025/logo-combined.webp",
    NITTE_LOGO: "/incridea2025/nitteLogoWhite.webp",
    GEARCLOCK: "/incridea2025/GearClock.webp",
    EVENT_BG: "/incridea2025/eventBg.webp",
    GAMER: "/incridea2025/gamer.webp",
    RYOKO: "/incridea2025/ryoko.webp",
    EXTERNAL_ACCOMMODATION: "/incridea2025/Incridea'25 External Accommodation List.xlsx",
  },
  // PROFILE: {
  //   TROPHY: "/incridea2025/profile/trophy.webp",
  // },
  // LOGIN: {
  //   BACKGROUND: "/incridea2025/login/bg-login.webp",
  //   GEAR: "/incridea2025/login/gear.webp",
  // },
  // LOADER: {
  //   SPACE_PORTAL_BG: "/incridea2025/loader/space-portal-bg.webp",
  //   SPACE_PORTAL: "/incridea2025/loader/space-portal.webp",
  //   EOELOGO: "/incridea2025/loader/Echoes_Of_Eternity_Logo.webp",
  //   HOURGLASS: "/incridea2025/loader/hourglass.webp",
  // },
  // AUDIO: {
  //   GEARCLOCK: "/incridea2025/audio/GearClockAudio.mp3",
  //   GEARSOUND: "/incridea2025/audio/gearsounds.mp3",
  //   TICK: "/incridea2025/audio/tick.mp3",
  //   LEVEL2: "/incridea2025/explore/audio/level2.mp3",
  // },
  EXPLORE: {
    LOADING_BACKGROUND: "/incridea2025/loading_background.webp",
    LOADING_FOREGROUND: "/incridea2025/loading_foreground.webp",
    STONE: "/incridea2025/stone.webp",
  },
  // PRONITE: {
  //   SHAAN: "/incridea2025/pronites/shaan.webp",
  //   SCREENTOP: "/incridea2025/pronites/screentop.webp",
  //   MASALACOFFEE: "/incridea2025/pronites/masalacoffee.webp",
  // },
  // LEADERBOARD: {
  //   LEVEL1: "/incridea2025/leaderboard/level1.png",
  //   LEVEL2: "/incridea2025/leaderboard/level2.png",
  //   LEVEL3: "/incridea2025/leaderboard/level3.png",
  //   LEVEL4: "/incridea2025/leaderboard/level4.png",
  //   TIMESTONE: "/incridea2025/leaderboard/timestone.png",
  // },
  "3D": {
    BLUE_STONE: "/incridea2025/models/blue_stone.glb",
    MEDIEVAL_BOUNDED: "/incridea2025/models/medieval_bounded_final.glb",
    PORTAL: "/incridea2025/models/portal.glb",
    RYOKU: "/incridea2025/models/ryoku.glb",
  },
  // ABOUT: {
  //   IMAGE1: "/incridea2025/about/1.webp",
  //   IMAGE2: "/incridea2025/about/2.webp",
  //   IMAGE3: "/incridea2025/about/3.webp",
  //   IMAGE4: "/incridea2025/about/4.webp",
  //   IMAGE5: "/incridea2025/about/5.webp",
  //   IMAGE6: "/incridea2025/about/6.webp",
  //   IMAGE7: "/incridea2025/about/7.webp",
  //   IMAGE8: "/incridea2025/about/8.webp",
  // },
  // GALLERY: {
  //   CAPTURELOGO: "/incridea2025/gallery/capture-logo.webp",
  //   BACKGROUND: "/incridea2025/gallery/galleryBg.webp",
  //   TABLET: "/incridea2025/gallery/tablet.webp",
  //   THUMBNAIL18: "/incridea2025/gallery/thumbnails/incridea18.webp",
  //   THUMBNAIL19: "/incridea2025/gallery/thumbnails/incridea19.webp",
  //   THUMBNAIL20: "/incridea2025/gallery/thumbnails/incridea20.webp",
  //   THUMBNAIL22: "/incridea2025/gallery/thumbnails/incridea22.webp",
  //   THUMBNAIL23: "/incridea2025/gallery/thumbnails/incridea23.webp",
  //   THUMBNAIL24: "/incridea2025/gallery/thumbnails/incridea24.webp",
  // },
  // LANDING: {
  //   LOADERBG: "/incridea2025/landing/loader/background.webp",
  //   LOADERCIRCLE: "/incridea2025/landing/loader/circle.webp",
  //   BACKGROUND: "/incridea2025/landing/background.webp",
  //   CLOCK: "/incridea2025/landing/clock.webp",
  //   EOETEXT: "/incridea2025/landing/eoelogo.webp",
  //   PILLAR: "/incridea2025/landing/pillar.webp",
  //   OBJECT1: "/incridea2025/landing/floatingObjects/1.webp",
  //   OBJECT2: "/incridea2025/landing/floatingObjects/2.webp",
  //   OBJECT3: "/incridea2025/landing/floatingObjects/3.webp",
  //   OBJECT4: "/incridea2025/landing/floatingObjects/4.webp",
  //   OBJECT5: "/incridea2025/landing/floatingObjects/5.webp",
  //   OBJECT6: "/incridea2025/landing/floatingObjects/6.webp",
  //   OBJECT7: "/incridea2025/landing/floatingObjects/7.webp",
  // },
};

export { ASSETS };
